### ISSUE TITLE
SAM templates

### ISSUE THREAD

**Issue by rastogia** [stelligent/cfn_nag#138] opened 2018-09-04 12:23 UTC
Hi,
Sorry to bother, but just tested with the sam template and I can still see the same error:
`$ cfn_nag -v
0.3.54
$ cfn_nag_scan --input-path wfs.yaml
wfs.yaml

| FAIL FATAL
|
| Unresolved logical resource ids: ["MyUserLambda.Alias", "MySubscribedDataLambda.Alias"]

Failures count: 1
Warnings count: 0`

Am I missing something pls?
Thanks

**Comment by erickascic** [comment] 2018-09-08 02:59
there were some enhancements added by others to support transforms, but i'm not sure where development is on that.  if you have an "offending" template, i will have some time to take a look this weekend

**Comment by erickascic** [comment] 2018-09-08 03:00
is this the same issue as #115?

**Comment by helpme1986** [comment] 2018-12-05 14:11
Hey, we have run into the same issue:

`  rLexTestStack:
    Condition: EnableTestStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./lex-example-bot.cf-template.yml
      Parameters:
        pLexSlotTypeFunctionArn: !Ref rLexSlotTypeFunction.Alias
        pLexIntentFunctionArn:   !Ref rLexIntentFunction.Alias
        pLexBotFunctionArn:      !Ref rLexBotFunction.Alias
        pLexBotAliasFunctionArn: !Ref rLexBotAliasFunction.Alias`

Is there anyway to at least suppress these fails? Ive taken a look at the list of rules but couldnt see this on there, the error is:

`------------------------------------------------------------------------------------------------------------------------
| FAIL FATAL
|
| Unresolved logical resource ids: ["rLexSlotTypeFunction.Alias", "rLexIntentFunction.Alias", "rLexBotFunction.Alias", "rLexBotAliasFunction.Alias"]

Failures count: 1
Warnings count: 0`

Thanks

**Comment by atkinsonm** [comment] 2019-05-03 21:33
I recommend closing as a duplicate of #115

**Comment by erickascic** [comment] 2019-05-04 16:01
dupe of #115

**Closed by erickascic** 2019-05-04 16:01 UTC
