### ISSUE TITLE
no implicit conversion of String into Integer (TypeError)

### ISSUE THREAD

**Issue by MaanasaDornala** [stelligent/cfn_nag#80] opened 2017-11-02 21:13 UTC
/usr/local/lib/ruby/gems/2.4.0/gems/cfn-model-0.1.4/lib/cfn-model/model/references.rb:19:in `[]': no implicit conversion of String into Integer (TypeError)
        from /usr/local/lib/ruby/gems/2.4.0/gems/cfn-model-0.1.4/lib/cfn-model/model/references.rb:19:in `resolve_security_group_id'
        from /usr/local/lib/ruby/gems/2.4.0/gems/cfn-model-0.1.4/lib/cfn-model/model/cfn_model.rb:44:in `find_security_group_by_group_id'
        from /usr/local/lib/ruby/gems/2.4.0/gems/cfn-model-0.1.4/lib/cfn-model/parser/ec2_instance_parser.rb:6:in `block in parse'
        from /usr/local/lib/ruby/gems/2.4.0/gems/cfn-model-0.1.4/lib/cfn-model/parser/ec2_instance_parser.rb:5:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/cfn-model-0.1.4/lib/cfn-model/parser/ec2_instance_parser.rb:5:in `map'
        from /usr/local/lib/ruby/gems/2.4.0/gems/cfn-model-0.1.4/lib/cfn-model/parser/ec2_instance_parser.rb:5:in `parse'
        from /usr/local/lib/ruby/gems/2.4.0/gems/cfn-model-0.1.4/lib/cfn-model/parser/cfn_parser.rb:56:in `block in post_process_resource_model_elements'
        from /usr/local/lib/ruby/gems/2.4.0/gems/cfn-model-0.1.4/lib/cfn-model/parser/cfn_parser.rb:50:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/cfn-model-0.1.4/lib/cfn-model/parser/cfn_parser.rb:50:in `post_process_resource_model_elements'
        from /usr/local/lib/ruby/gems/2.4.0/gems/cfn-model-0.1.4/lib/cfn-model/parser/cfn_parser.rb:42:in `parse'
        from /usr/local/lib/ruby/gems/2.4.0/gems/cfn-nag-0.3.7/lib/cfn-nag/cfn_nag.rb:60:in `audit'
        from /usr/local/lib/ruby/gems/2.4.0/gems/cfn-nag-0.3.7/lib/cfn-nag/cfn_nag.rb:44:in `block in audit_aggregate_across_files'
        from /usr/local/lib/ruby/gems/2.4.0/gems/cfn-nag-0.3.7/lib/cfn-nag/cfn_nag.rb:41:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/cfn-nag-0.3.7/lib/cfn-nag/cfn_nag.rb:41:in `audit_aggregate_across_files'
        from /usr/local/lib/ruby/gems/2.4.0/gems/cfn-nag-0.3.7/lib/cfn-nag/cfn_nag.rb:25:in `audit_aggregate_across_files_and_render_results'
        from /usr/local/lib/ruby/gems/2.4.0/gems/cfn-nag-0.3.7/bin/cfn_nag_scan:28:in `<top (required)>'
        from /usr/local/bin/cfn_nag_scan:23:in `load'
        from /usr/local/bin/cfn_nag_scan:23:in `<main>'

**Comment by erickascic** [comment] 2017-11-02 21:41
@MaanasaDornala do you have a test template I can use to reproduce this exception?

**Comment by MaanasaDornala** [comment] 2017-11-02 21:49
@erickascic the problem is that we cannot share the template, however i will see how can we reproduce with some sample file

**Comment by erickascic** [comment] 2017-11-02 21:51
@MaanasaDornala understood - can you describe just the security group related resources?

**Comment by MaanasaDornala** [comment] 2017-11-02 21:58
@erickascic  we are using "SecurityGroupIds" under EC2::Instance

**Comment by MaanasaDornala** [comment] 2017-11-02 22:07
@erickascic if i remove the SecurityGroupIds under EC2::Instance , it is working

**Comment by erickascic** [comment] 2017-11-02 22:24
@MaanasaDornala think I may have it figured out - is the value of SecurityGroupIds a Ref to a parameter of type List<AWS::EC2::SecurityGroup::Id>?

**Comment by erickascic** [comment] 2017-11-02 22:38
@MaanasaDornala give version 0.3.8 of cfn-nag a go.  I believe I have fixed the underlying problem.

**Comment by ManasaDornala** [comment] 2017-11-03 11:23
@erickascic i couldn't see 0.3.8 version from gem install, the latest is 0.3.7

**Comment by ManasaDornala** [comment] 2017-11-03 11:27
@erickascic i could see that you committed yesterday, let me try

**Comment by erickascic** [comment] 2017-11-03 11:28
0.3.8 looks like it is there in ruby gems.org?

https://rubygems.org/gems/cfn-nag/versions/0.3.8
________________________________

**Closed** 2017-11-07 19:46 UTC
